### ISSUE TITLE
Split of L0-Occluded Pascal3D+

### ISSUE THREAD

**Issue by YoungXIAO13** [Angtian/NeMo#2]
Hi, 

Thanks for the great work and sharing the code!

I've got one question about the non-occluded split of Pascal3D+. In your paper, StarMap gets 89% Acc30 while the author of StarMap only reported an accuracy at 82% in their paper, I suppose this difference is resulted from a different dataset split for evaluation. Could you tell me how you get the non-occluded test images on Pascal3D+ and is there any difference between the images in occlusion L0, L1, L2, and L3?

**Comment by Angtian** [comment]
Hello Yang,
Thanks for proposing the issue.
Yes, we use a different data splitting from Starmap. We run the StarMap official implementation on our data splits and report that result.
Splitting Details: The Pascal3D+ dataset includes 2 subsets which images are from ImageNet or Pascal VOC. The Starmap uses ImageNet Train, ImageNet Test and Pascal Train for training, and uses pascal test for testing. Due to we don't have occluded image for Pascal subset, we only use ImageNet Train for training, and ImageNet Test for testing. Also, we suggest that there is a domain different between ImageNet subset and Pascal subset, so we think the StarMap settings will also involve some domain transfer problem.
Difference between the images in occlusion L0, L1, L2, and L3: Images in different occ levels are the same set of images but superimposed with different occlusions. We leveled them with the ratio of occluded area of the object.

**Comment by YoungXIAO13** [comment]
Thanks for your instant reply and detailed explanation! That solves my issue.
